### ISSUE TITLE
Set min identifier to 1

### ISSUE THREAD

**Issue by eonist** [sindresorhus/swiftlint-sindre#2]
To support code like this:

```swift
public enum ECLevel: String, CaseIterable { 
   case l = "L"
   case m = "M"
   case q = "Q"
   case h = "H"
}
```
or this

```swift
for i in (0..<5) {
   print(\(i))
}

```

Change .yml to: 
```
identifier_name:
  max_length:
    warning: 100
    error: 100
  min_length:
    warning: 1  // 👈 was 2
    error: 1 // 👈 was 2
```

**Comment by sindresorhus** [comment]
The rule is intentional. Single-character variable names reduce readability.

The above should be:

```swift
public enum ErrorCorrectionLevel: String, CaseIterable {
	case low = "Low"
	case medium = "Medium"
	case quality = "Quality"
	case high = "High"
}
```

**Comment by eonist** [comment]
So just out of professional curiosity. 

Would you write: 

`let x = 2` 👉 `let xVal = 2`
`for i in (0..<5){ print(i) }` 👉 `for index in (0..<5){ print(index) }`

**Comment by sindresorhus** [comment]
> let x = 2 👉 let xVal = 2

`x` and `y` are fine if they're actually referring to coordinates. 

https://github.com/sindresorhus/swiftlint-sindre/blob/471f96b56cdc3ad34e059dc0ca3dc46fae72b7be/.swiftlint.yml#L148-L149

> for i in (0..<5){ print(i) } 👉 for index in (0..<5){ print(index) }

Yes, I prefer spelling it out, but I know this one is contentious.
