### ISSUE TITLE
Add instructions to readme

### ISSUE THREAD

**Issue by eonist** [sindresorhus/swiftlint-sindre#3]
the swift-lint official instructions are so gnarly. 

1. install swift-lint: [https://github.com/realm/SwiftLint/releases](https://github.com/realm/SwiftLint/releases)   

2. Add `.swiftlint.yml` to your xcode project folder
  - Example of swift-lint rule set: [https://github.com/realm/SwiftLint/blob/master/.swiftlint.yml](https://github.com/realm/SwiftLint/blob/master/.swiftlint.yml)
  - Another swift-lint example from Sindre Sorhus project GifSki: [https://github.com/sindresorhus/gifski-app/blob/master/.swiftlint.yml](https://github.com/sindresorhus/gifski-app/blob/master/.swiftlint.yml)

3. Add swift-lint script to your xcodeproject:

  - XCode 👉 Build phases
  - Click "plus-button" 👉 Add run script
  - Paste in the bellow:

```swift
if which swiftlint >/dev/null; then
  swiftlint
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

4. Build the project to see some swift-lint warnings

5. Add a swift-lint badge to your github project [![SwiftLint Sindre](https://img.shields.io/badge/SwiftLint-Sindre-hotpink.svg)](https://github.com/sindresorhus/swiftlint-sindre) `[![Swift-lint Sindre](https://img.shields.io/badge/swift--lint-sindre-brightgreen.svg)](https://github.com/sindresorhus/swiftlint-sindre)`
`

**Comment by sindresorhus** [comment]
You would help a lot more people if you instead opened a PR on SwiftLint to improve the instructions there.

**Comment by eonist** [comment]
SwiftLint is the can. `SwiftLint Sindre` is the can-opener. And a much better vessel for change IMO but I see your point about wanting to have less to maintain.

**Comment by sindresorhus** [comment]
It's not just having to have more to maintain. It's that there's probably just a dusin people that will use this module, while improving the SwiftLint readme will improve the experience for many thousands of devs.

**Comment by eonist** [comment]
I feel like this is the start of XO but for swift ;) SwiftLint is unsexy and raw. You need something sexy to get people going ✌️
